name: Release

on:
  workflow_dispatch: # Trigger manually
  push:
    branches:
      - master

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Determine next version
        id: versioning
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          patchList: fix, refactor, ci, docs, perf, style, test
      - name: Print version output
        run: |
          echo next version: ${{steps.version.outputs.next}}
      - name: Update Maven version
        # TODO does not seem to work
        run: mvn -B versions:set -DnewVersion=${{steps.version.outputs.next}} -DgenerateBackupPoms=false
      - name: Generate changelog
        id: changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit version and changelog changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add pom.xml CHANGELOG.md
          git commit -m "Bump version to ${{steps.version.outputs.next}}"
      - name: Create release tag
        uses: actions/create-release@v1
        with:
          tag_name: ${{steps.version.outputs.next}}
          release_name: Release ${{steps.version.outputs.next}}
          body: |
            Changes in this release:
            ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
