name: Release

on:
  workflow_dispatch: # Trigger manually
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Determine next version
        id: version
        uses: wemogy/next-version-action@2.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Update Maven version
        run: mvn -B versions:set -DnewVersion=${{ steps.version.outputs.next_version }} -DgenerateBackupPoms=false
      - name: Generate changelog
        id: changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit version and changelog changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add pom.xml CHANGELOG.md
          git commit -m "Bump version to ${{ steps.version.outputs.next_version }}"
      - name: Create release tag
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.version.outputs.next_version }}
          release_name: Release ${{ steps.version.outputs.next_version }}
          body: |
            Changes in this release:
            ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
